
podTemplate(
  inheritFrom: 'jenkins-agent',
  containers: [
    containerTemplate(name: 'kubectl', image: 'alpine/k8s:1.24.13', alwaysPullImage: false, ttyEnabled: true, command: 'cat')
  ]
) {
  node(POD_LABEL) {
    stage('checkout scm') {
      checkout scm
    }



    stage('Deploy on aks'){
      container('kubectl') {
        withCredentials([file(credentialsId: 'k8s-config', variable: 'KUBECONFIG')]){
          echo 'Applying K8s manifests...'
          sh "kubectl apply -f kubernetes/ --set kubernetes/deployment.yaml/spec.containers.image =$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG "
          sh "cat kubernetes/deployment.yaml"

        }
      }
    }
  }
}