podTemplate(
  inheritFrom: 'jenkins-agent',
  containers: [
    containerTemplate(name: 'docker-container', image: 'docker:19.03.1-dind', alwaysPullImage: false, ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'node-container', image: 'bitnami/node:18.4.0', alwaysPullImage: false, ttyEnabled: true, command: 'cat')
  
]

){
  node(POD_LABEL) {
    
    stage('Checkout leto project') {
      withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'leto-modelizer']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/leto-modelizer.git']]])
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'terrator-plugin']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/terrator-plugin.git']]])
      }
    }
    stage('Checkout cicd folder') {
      dir('leto-gitops'){
        checkout scm
      }
    }
   

    stage('Build / Tests') {
      container('node-container') {
        
          dir('leto-modelizer') {
            sh """
            node -v
            npm -v
            cat package.json
            npm install
            # npm install --save ../jenkinator-plugin
            # npm install --save ../terrator-plugin
            # npm install --save ../kubernator-plugin
            # npm install --save ../githubator-plugin
            #echo -en '{ "plugins": ["jenkinator-plugin", "terrator-plugin", "kubernator-plugin"] }' > plugin.config.json
            #npm run plugin:init
            npm run build
            """
          }
         
        
      }
    }
    

   
  }
}