image_full_name = 'leto'
image_tag = '1.0.0'


podTemplate(
  inheritFrom: 'jenkins-agent',
  containers: [
    containerTemplate(name: 'docker-container', image: 'docker:19.03.1-dind', alwaysPullImage: false, ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'node-container', image: 'node:alpine', alwaysPullImage: false, ttyEnabled: true, command: 'cat'),
  ]
){
  node(POD_LABEL) {
    
    stage('Checkout leto project') {
      withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'leto-modelizer']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/leto-modelizer.git']]])
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'leto-modelizer-plugin-core']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/leto-modelizer-plugin-core.git']]])
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'leto-modelizer-plugin-cli']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/leto-modelizer-plugin-cli.git']]])
        checkout([$class: 'GitSCM', branches: [[name: "main"]], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'terrator-plugin']], userRemoteConfigs: [[url: 'https://github.com/samar-belhadj/terrator-plugin.git']]])
      }
    }
    stage('Checkout cicd folder') {
      dir('leto-gitops'){
        checkout scm
      }
    }
   /* stage('Get Image Tag') {
      dir('leto-modelizer'){
        
        packageJSON = readJSON file: 'package.json'
        version = packageJSON.version
        image_tag = "${env.BUILD_ID}-${version}"
      }
    }*/
    stage('Prepare Plugins') {
      dir('leto-modelizer') {
        sh """
        rm -rf package-lock.json
        sed -i 's,github:ditrit/,git+https://github.com/samar-belhadj/,g' package.json
        sed -i 's,leto-modelizer-plugin-core#.*",leto-modelizer-plugin-core",g' package.json
        sed -i 's,leto-modelizer-plugin-cli#.*",leto-modelizer-plugin-cli",g' package.json
        """
      }
      dir('leto-modelizer-plugin-core') {
        sh """
        rm -rf package-lock.json demo/package-lock.json
        sed -i 's,github:ditrit/,git+https://github.com/samar-belhadj/,g' package.json
        """
      }
      
      dir('terrator-plugin') {
        sh """
        rm -rf package-lock.json
        sed -i 's,github:ditrit/,git+https://github.com/samar-belhadj/,g' package.json
        sed -i 's,leto-modelizer-plugin-core#.*",leto-modelizer-plugin-core",g' package.json
        """
      }
      
    
    }
    stage('Build / Tests') {
      container('node-container') {
        
          dir('leto-modelizer') {
            sh """
            node -v
            npm install npm@latest -g
            npm install  
            npm install --save ../terrator-plugin
            echo '{ "plugins": ["terrator-plugin"] }'>plugin.config.json
            cat plugin.config.json
            npm run plugin:init
            npm run build
            """
          }
          
        
      }
    }

    stage('Build / Push Docker Image'){
      container('docker-container') {
       
          withCredentials([file(credentialsId: 'docker-config', variable: 'DOCKER_CONFIG')]){
            dir('leto-modelizer') {
              sh """
              docker build -t samarbelhadj/${image_full_name}:${image_tag} -f ../leto-gitops/docker/Dockerfile .
              mkdir /usr/docker_config && cp "$DOCKER_CONFIG" /usr/docker_config/
              docker --config /usr/docker_config/ push  samarbelhadj/${image_full_name}:${image_tag}
              """
            }
          }
        
      }
    }

    
   
  }
}